version: '3.9'

services:
  db:
    image: postgres
    restart: always
    # Optional: Map the container port to a host port to be able to connect with a local db client 
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/psql-init/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres_data:/var/lib/postgresql/data/

  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
      target: dev
    #restart: always
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ../:/home/web/code
    ports:
      - 9000:9000

volumes:
  postgres_data:
